### ISSUE TITLE
settings.timing.tWTR expressed in nanoseconds but used as cycles

### ISSUE THREAD

**Issue by JohnSully** [enjoy-digital/litedram#13]
In multiplexer.py the line: fsm.delayed_enter("WTR", "READ", settings.timing.tWTR-1) uses the tWTR parameter.  However in the modules its expressed in nanoseconds.

Other parameters such as tRP also expressed in nanoseconds undergo a transformation elsewhere to get converted into cycles - however tWTR never does.  This greatly exaggerates the delay switching between write and read.

**Comment by enjoy-digital** [comment]
Thanks, tWTR is expressed in sys_clk cycles. I fixed that in modules and will probably improve modules definition soon. (allowing defining speedgrage and selecting the max between number of cycles and value in ns as expressed in the datasheet for tWTR)
