### ISSUE TITLE
1:2 7-series Phy doesn't issue commands in write mode

### ISSUE THREAD

**Issue by JohnSully** [enjoy-digital/litedram#15]
Underlying issue appears to be that the wrcmdphase has the same value as the wrphase.  The wrphase wins and the command is silently dropped (but the bank machine thinks it was sent).

Forcing wrcmdphase to 1 appears to work.

**Comment by enjoy-digital** [comment]
Thanks, I'll have a look at wrphase/wrcmdphase computation. Not sure forcing wrcmdphase to 1 really work because we are no longer ensuring cwl latency between cmd and data. We will maybe have to play configure additive latency to make sure cwl + al is odd.

**Comment by JohnSully** [comment]
That was a hack to verify.

If they need the same phase then we can arbitrate instead of always choosing wrcmd.

**Comment by enjoy-digital** [comment]
Moved to https://github.com/enjoy-digital/litedram/issues/29 which is more generic.
