### ISSUE TITLE
tRRD and tFAW not respected

### ISSUE THREAD

**Issue by JohnSully** [enjoy-digital/litedram#17]
This is hidden when only using a single user port because the time to complete a command exceeds these timings.  However when operating with multiple ports it is possible to exceed both tRRD and tFAW as the mux will issue a row command every cycle if it receives a command from a bank to do so.

**Comment by JohnSully** [comment]
https://github.com/enjoy-digital/litedram/pull/18

**Comment by enjoy-digital** [comment]
Thanks, since https://github.com/enjoy-digital/litedram/pull/19 is merged and covers this, i think we can close this.
