### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litedram#180]
Currently CI for litedram is running on travis-ci.org. Travis-CI is migrating everyone to Travis-CI.com as it has a lot more features.

We are also paying for @enjoy-digital to also have up to 50+ simultaneous but that only works on Travis-CI.com (not Travis-CI.org). So that should make Travis builds a lot faster for something like LiteDRAM which has a lot builds (as they will all run in parallel.

There should be a "migrate" button somewhere on the travis-ci.org or travis-ci.com page for LiteDRAM somewhere. As @enjoy-digital is a user rather than an organization, only @enjoy-digital can click the migrate button.

See https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by enjoy-digital** [comment]
Thanks, i don't remember why litedram was on travis-ci.org and others repositories on travis-ci.com...
