### ISSUE TITLE
Add Halfrate GENSDRPHY

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/litedram#183]
On small FPGAs with SDRAM, we are currently running the SDRAM at the CPU frequency while in most of the cases we could probably run the SDRAM at 2x the CPU frequency (for example 50MHz CPU/100MHz SDRAM, 66MHz CPU/133MHz SDRAM). To support this, we could generate a `sys2x` clock with the main PLL of the design and create a wrapper around the GENSDRPHY that would do the clock/DFI adaptation.

**Comment by rowanG077** [comment]
This issue can be closed I think?

**Comment by enjoy-digital** [comment]
@rowanG077:  yes this is implemented, i just wanted to test it on various SDRAM boards before closing. This is now done.
