### ISSUE TITLE
Support for DRAM on Lattice ICE40HX devices?

### ISSUE THREAD

**Issue by adamfeuer** [enjoy-digital/litedram#215]
Hi, is LiteDRAM known to work on Lattice ICE40HX devices? I didn't see an example for it... has anyone tried it yet?

**Comment by daveshah1** [comment]
I believe it has been used successfully for SDRAM as part of a LiteX SoC. There is no iCE40 PHY for any of the DDR variants.

**Comment by adamfeuer** [comment]
@daveshah1 Thanks. SDRAM would work for me. 

Does it make sense to create a DDR PHY for the the iCE40? If so, what would it take to do it? How were the existing DDR PHYs created and debugged (for instance the [s6ddrphy.py](https://github.com/enjoy-digital/litedram/blob/master/litedram/phy/s6ddrphy.py)?)

**Comment by adamfeuer** [comment]
I see there's a DDR PHY for ECP5. That would also work for me. Thanks.
