### ISSUE TITLE
Generating a PHY only design

### ISSUE THREAD

**Issue by Neosar** [enjoy-digital/litedram#243]
Hello,

I would like to know if it is possible to generate only PHY (like Xilinx MIG) since I need to test my custom DDR4 memory controller. I know it can be done using MIG, but my controller uses the DFI interface and MIG does not support that, unfortunately.

Thank you.

**Comment by enjoy-digital** [comment]
Hello @Neosar,

It's possible to generate a standalone controller integrating the PHY + Core + CPU (for the initialization) + User interfaces but just generating the PHY would require a custom generator or modifications to the current one: https://github.com/enjoy-digital/litedram/blob/master/litedram/gen.py This is something we could do, but would requires at least 1 or 2 days of work.
