### ISSUE TITLE
Generation with AXI interface

### ISSUE THREAD

**Issue by lindajames101** [enjoy-digital/litedram#254]
Is there any documentation or procedure for generation with axi signals?

**Comment by enjoy-digital** [comment]
Hi @lindajames101,

to add AXI User ports, you can look at the LiteDRAM generator: https://github.com/enjoy-digital/litedram/blob/master/litedram/gen.py#L596-L647 or try to generate the cores as a standalone with `cd examples && litedram_gen arty.yml` that exposes an AXI User port: https://github.com/enjoy-digital/litedram/blob/master/examples/arty.yml#L35-L38.
