### ISSUE TITLE
The MAX sys_clk_freq supported of DDR4

### ISSUE THREAD

**Issue by uxilinx** [enjoy-digital/litedram#272]
Set sys_clk_freq=300 M in the .yml file. When gen.py is executed to generate bit file, the OSRDESE3 min period slack violation occurs in sys4x_pll_clk and the max skew violation occurs in sys_clk. Therefore, is sys_clk_freq set to 300 M not supported?

**Comment by enjoy-digital** [comment]
Hi @uxilinx,

the sys_clk_freq is limited by the max frequency of the clock buffer: 725/4=181MHz on a -2 Ultrascale, 850/4=212.5 on a -3 Ultrascale. It will probably work at higher speeds.
