### ISSUE TITLE
Allow all CL/CWL combinations to be used with DDR3

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/litedram#29]
Some CL/CWL combinations are not possible since cmd_phase and dat_phase will be the same and there is no arbitration.

An assert (assert cmd_phase != dat_phase) is currently  implemented in the code to prevent this case, but this limits the possible CL/CWL combinations.

We should probably remove this limitation by doing arbitration between cmd and data phases when both are valid.

**Comment by JohnSully** [comment]
Can you explain the problem a bit more?  I'm not saying its correct, but when I just force the phases to be different it doesn't see any timing errors.  Which timing parameter will be violated?

**Comment by enjoy-digital** [comment]
Fixed with https://github.com/enjoy-digital/litedram/commit/7b427391bd067fa53e5f3002493f64a41092da08. In the first version of the code i over-restricted things (relation between cmd/dat phases), which was not needed.
