### ISSUE TITLE
LDDR5 Support

### ISSUE THREAD

**Issue by pjattke** [enjoy-digital/litedram#291]
Hi all, 
From what I have seen in #239 and #63, the LDDR4 support is not complete yet: is this correct and to which extent can LPDDR4 be used with the current code? Given that, I guess that LPDDR5 support is not expected to come in near future?

Keep up the great work and many thanks for your feedback!

**Comment by kgugala** [comment]
hi @pjattke LPDDR4 is usable with litedram meaning you can train the lines, read and write the memory the features listed in #239 are optional

**Comment by pjattke** [comment]
Hi @kgugala 
That's great news, thanks!
