### ISSUE TITLE
Can't calibrate

### ISSUE THREAD

**Issue by JohnSully** [enjoy-digital/litedram#37]
This is related to my other issue where calibration hangs.  However even when working around it with a delay between reads and writes calibration still fails.  It was working about a month ago.

Trying to figure it out on my own, but I'm running out of ideas.

**Comment by JohnSully** [comment]
I’m currently testing with 1:4 @ 87.5mhz. Same problems as 1:2

**Comment by enjoy-digital** [comment]
I don't see the issue while testing with arty-soc/arty_ddr3 for 1:2 and 1:4. It's probably related to our something on our common project. Let's discuss that together by mail.
