### ISSUE TITLE
1:2 Sequential Access Throughput is Lower Than Expected

### ISSUE THREAD

**Issue by JohnSully** [enjoy-digital/litedram#40]
The 1:2 Phy only gets 64% bus efficency with a sequential read pattern.  The 1:4 is capable of 97%.  

My theory is the arbitrator in the bank machine mux is to blame.

**Comment by enjoy-digital** [comment]
Thanks. Are you going to have a look or do you want i look at that? (Not sure i'll be able to look at it in the next days). I'm planning to add unit-test of the internal modules of the cores to help figuring out this kind of things.

**Comment by JohnSully** [comment]
I’ll take a look

**Comment by enjoy-digital** [comment]
Fixed with https://github.com/enjoy-digital/litedram/commit/06c8c2afcf1e3c6cff1f7f2f38e6d9b352220055 that is indeed reverting to old code.
