### ISSUE TITLE
tFAW is too pessimistic

### ISSUE THREAD

**Issue by JohnSully** [enjoy-digital/litedram#50]
Haven't had a chance to look into why yet, but I've temporarily disabled it locally.  Its a major bottleneck the difference between 42% and 80% bus efficiency on my random write test.  I'm not getting tFAW errors with it disabled which makes me think its not correct.

**Comment by JohnSully** [comment]
Seems the timing parameter itself is off.  Datasheet says 50ns, however I'm seeing it set as 16 cycles @ 160mhz = 100ns.

**Comment by enjoy-digital** [comment]
Thanks, will look at that.

**Comment by enjoy-digital** [comment]
You are probably using the default speedgrade (DDR3-1600). You need to pass speedgrade parameter to the module: speedgrage="800").
