### ISSUE TITLE
Add a test design for each of the DDR technologies

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litedram#52]
It would be good to have at least one test for each of the technology group;
 * SDRAM
 * DDR
 * LPDDR
 * DDR2
 * DDR3

I believe DDR3 is the primary one covered by tests at the moment?

**Comment by enjoy-digital** [comment]
I'll try to add that to the examples and require that examples are building correctly before integrating changes.
This should prevent issues like https://github.com/enjoy-digital/litedram/issues/51.

**Comment by enjoy-digital** [comment]
https://github.com/enjoy-digital/litex/blob/master/test/test_targets.py should cover most of this. DDR and LPDDR are missing, i'll try to add more configurations to test.

**Comment by enjoy-digital** [comment]
This is now covered by the new Travis-CI tests that are testing all SDRAM modules.
