### ISSUE TITLE
Example Constraint File

### ISSUE THREAD

**Issue by JohnSully** [enjoy-digital/litedram#56]
It would be nice to have an example constraint file for high speed operation (800MT/s and above).

Specifically to answer the questions:
- Slew fast/slow (and are A pins different than Q pins given they are half the toggle rate)
- IN_TERM values
- SSTL15/SSTL15_R? (And DDR3L examples)

**Comment by enjoy-digital** [comment]
The LiteX platforms can be used as example:
Arty: https://github.com/enjoy-digital/litex/blob/master/litex/boards/platforms/arty.py#L93
KC705: https://github.com/enjoy-digital/litex/blob/master/litex/boards/platforms/kc705.py#L108
and others boards.
I'll point to them when describing the examples.
