### ISSUE TITLE
Add migen testbenches for the core

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/litedram#57]
The core is currently tested with high level simulation of the full controller which is not practical and slow.

We need good migen testbenches for the cores to:
- ensure we don't have regression when doing changes. 
- ensure all timings parameters are handled correctly.
- provide a better way to evaluate efficiency according to the access pattern.
- find the best architecture.

**Comment by mithro** [comment]
This actually sounds like a pretty good summer of code or other student style project?

**Comment by enjoy-digital** [comment]
Indeed, i would be happy to provide a skeleton and then help with giving directions.

**Comment by enjoy-digital** [comment]
This work will be done in #155 and #156.
