### ISSUE TITLE
Add support for ice40 with sdram (CAT board?)

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litedram#7]
Most ice40 boards have SRAM which makes them useless for running real OSes like Linux. In theory you should be able to use the SDRAM controller from litedram on the ice40.

The CAT board https://hackaday.io/project/7982-cat-board is the only ice40 boards I've found with SDRAM so far.

**Comment by mithro** [comment]
See https://github.com/knielsen/ice40-stm32-sdram for @knielsen who is also interested in this.

**Comment by enjoy-digital** [comment]
ice40 should already be supported with the generic phy (https://github.com/enjoy-digital/litedram/blob/master/litedram/phy/gensdrphy.py). Closing, but if someone needs help, i can answer here.
