### ISSUE TITLE
SDRAM CKE as optional

### ISSUE THREAD

**Issue by AnttiLukats** [enjoy-digital/litedram#87]
make it easy to not export simple SDRAM CKE pin, as it is optional and may be tied hi on target PCB, and yes it may be that there is not a single unused pin left to assign this signal too

**Comment by enjoy-digital** [comment]
That's already the case for the SDRAM PHY: 
https://github.com/enjoy-digital/litedram/blob/master/litedram/phy/gensdrphy.py#L59-L62
cke/cs_n pins will only be used if specified in your platform file.

**Comment by AnttiLukats** [comment]
ah, I hoped it MAY so, but good and thanks,, we have a board where we will tie CKE to 1, hm actually we could tie CS also to gnd, I guess
