### ISSUE TITLE
memtest passing when one DQn pin is not connected

### ISSUE THREAD

**Issue by AnttiLukats** [enjoy-digital/litedram#89]
we get memtest OK results while one of the DQ pins was not connected due to error in platform, so the dq port in top had only 15 pins, but memtest is reporting OK ?

**Comment by enjoy-digital** [comment]
This was reporting ok since the controller was in fact working on 8-bit instead of 16, i'll add some assertions to report theses kind of errors earlier.

**Comment by enjoy-digital** [comment]
This will now be detected with https://github.com/enjoy-digital/litedram/commit/8573c22cc1a10c89dcff3e838387a676c3b2ac5e.
